# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Continous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # 5.4.0
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # 3.0.1
