# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: "Build & Release"
    environment:
      name: Cloudflare Pages
      url: "${{ steps.deploy.outputs.deployment-url }}"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # 4.2.2
      - uses: "dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e" # 8.0.0
        with:
          call: "sitegen export --path _output/"
      - uses: "cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65" # 3.14.1
        id: deploy
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          command: "pages deploy _output/ --project-name=git-io --branch=${{ github.ref_name }} --commit-hash=${{ github.head }}"
